services:
  - type: web
    name: flowers-animation
    env: static
    buildCommand: null
    staticPublishPath: ./
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
