services:
  - type: web
    name: flowers-animation
    env: static
    buildCommand: null
    staticPublishPath: ./
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
